baseURL = "https://www.yucklys.com/"
languageCode = "zh-cn"
title = "Yucklys的小站"
theme = "jane"
googleAnalytics = "UA-122649646-1"
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
paginate = 3
defaultContentLanguage = "zh-cn"

# Highlight options. 
# See https://gohugo.io/content-management/syntax-highlighting/ 
PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences 
PygmentsUseClasses = true # Use CSS classes to format highlighted code 
PygmentsCodefencesGuessSyntax = true 
PygmentsOptions = "linenos=table" 

[author]
  name = "Yucklys"

[languages.zh-cn]
  languageCode = "zh-cn"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "主页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[params]
  since = "2018"
  homeFullContent = false
  rssFullContent = true
  keywords = ["yucklys", "blog", "rust"]
  dateFormatToUse = "2006-01-02"
  toc = true

[params.social]
  a-email = "mailto:yucklys687@gmail.com"
  b-github = "https://github.com/Yucklys"

[params.valine]
  enable = true
  appId = 'KUblOPKlq50rTW3lTrMNovfT-gzGzoHsz'
  appKey = 'gi4gkH2uAcjg12ua1Hg5DPAj'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm' 
  placeholder = '喵喵喵?'
  visitor = true
